apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dental-backend
  template:
    metadata:
      labels:
        app: dental-backend
    spec:
      containers:
      - name: dental-backend
        image: atanasoska/dental-backend:latest
        imagePullPolicy: Always
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dental-db-secret
              key: password
        
        - name: DATABASE_URL
          value: "postgresql+psycopg2://postgres:$(DB_PASSWORD)@dental-db-service:5432/dental_db"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "dental-kv-provider"